version: "3"

services:
  flarum:
    image: mondedie/flarum:stable
    container_name: flarum
    env_file:
      - /home/ubuntu/flarum/flarum.env
    volumes:
      - /home/ubuntu/flarum/assets:/flarum/app/public/assets
      - /home/ubuntu/flarum/extensions:/flarum/app/extensions
      - /home/ubuntu/flarum/storage/logs:/flarum/app/storage/logs
      - /home/ubuntu/flarum/nginx:/etc/nginx/flarum
      - /home/ubuntu/flarum/vendor:/flarum/app/vendor
    ports:
      - 80:8888
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=flarum
      - MYSQL_USER=flarum
      - MYSQL_PASSWORD=password
    volumes:
      - /home/ubuntu/flarum/db:/var/lib/mysql